In [1]:
import pandas as pd

In [4]:
# Read in Master Rows

mri = pd.read_csv('inner_merge.csv', index_col=0)

mro = pd.read_csv('outer_merge.csv', index_col=0)

In [6]:
print(mro.shape)
mro.head(2)

(11789, 30)

,region_name_ppsft,state_code,metro_ppsft,county_name,size_rank_ppsft,pct_change_ppsft,ppsft_2017,state_full,loc_full,n_trips,...,Fire,Flood,Human Cause,Hurricane,Other,Severe Ice Storm,Severe Storm(s),Snow,Tornado,Volcano
0,New York,NY,New York,Queens,1,0.092089,483,New York,"Queens, New York",4519293.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,0.080575,432,California,"Los Angeles, California",36765826.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
mro.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11789 entries, 0 to 11788
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   region_name_ppsft               11789 non-null  object
 1   state_code                      11789 non-null  object
 2   metro_ppsft                     10859 non-null  object
 3   county_name                     11789 non-null  object
 4   size_rank_ppsft                 11789 non-null  int64
 5   pct_change_ppsft                11788 non-null  float64
 6   ppsft_2017                      11789 non-null  int64
 7   state_full                      11789 non-null  object
 8   loc_full                        11789 non-null  object
 9   n_trips                         11789 non-null  float64
 10  state_min_wage                  11789 non-null  float64
 11  fed_min_wage                    11789 non-null  float64
 12  effective_min_wage              11789 non-null  float64
 13  cpi_average                     11789 non-null  float64
 14  prp_taxes_mill                  11789 non-null  int64
 15  prp_taxes_per_capita            11789 non-null  int64
 16  prp_taxes_perc_general_rev      11789 non-null  object
 17  prp_taxes_perc_personal_income  11789 non-null  object
 18  Biological                      34 non-null     float64
 19  Earthquake                      12 non-null     float64
 20  Fire                            41 non-null     float64
 21  Flood                           44 non-null     float64
 22  Human Cause                     14 non-null     float64
 23  Hurricane                       13 non-null     float64
 24  Other                           12 non-null     float64
 25  Severe Ice Storm                14 non-null     float64
 26  Severe Storm(s)                 34 non-null     float64
 27  Snow                            2 non-null      float64
 28  Tornado                         14 non-null     float64
 29  Volcano                         11 non-null     float64
dtypes: float64(18), int64(4), object(8)
memory usage: 2.8+ MB

In [17]:
mro = mro[['region_name_ppsft', 'state_code', 'metro_ppsft', 'county_name',
       'size_rank_ppsft', 'pct_change_ppsft', 'ppsft_2017', 'state_full',
       'loc_full', 'n_trips', 'state_min_wage', 'fed_min_wage',
       'effective_min_wage', 'cpi_average', 'prp_taxes_mill',
       'prp_taxes_per_capita', 'prp_taxes_perc_general_rev',
       'prp_taxes_perc_personal_income', 'Earthquake', 'Fire',
        'Flood', 'Hurricane', 'Severe Ice Storm', 'Severe Storm(s)',
        'Tornado'
           ]]

In [ ]:
ascending=[
                    False,
                    True,
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    False]

                ascending=[
                    True,
                    False,
                    True,
                    True,
                    True,
                    True,
                    True,
                    True,
                    True,
                    True,
                ]

In [26]:
# Lets start wth a massive Sort Values

rank1 = mro.sort_values(by=['ppsft_2017',
                    'n_trips',
                    'prp_taxes_mill', 
                    'state_min_wage', 
                    'Flood',
                    'Hurricane',
                    'Earthquake',
                    'Fire',
                    'Severe Storm(s)',
                    'Tornado'],
                ascending=[
                    True,
                    False,
                    True,
                    True,
                    True,
                    True,
                    True,
                    True,
                    True,
                    True,
                ])
rank1.head(2)

,region_name_ppsft,state_code,metro_ppsft,county_name,size_rank_ppsft,pct_change_ppsft,ppsft_2017,state_full,loc_full,n_trips,...,prp_taxes_per_capita,prp_taxes_perc_general_rev,prp_taxes_perc_personal_income,Earthquake,Fire,Flood,Hurricane,Severe Ice Storm,Severe Storm(s),Tornado
9335,Mahanoy City,PA,Pottsville,Schuylkill,6911,0.043478,25,Pennsylvania,"Schuylkill, Pennsylvania",877910.0,...,1584,15.5%,2.8%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9340,Ashland,PA,Pottsville,Schuylkill,8163,0.022436,25,Pennsylvania,"Schuylkill, Pennsylvania",877910.0,...,1584,15.5%,2.8%,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# ok let's see what we can do with the top row..

rank1.iloc[0]['loc_full']

# 'Schuylkill, Pennsylvania'

# Can we plug this into the AirDNA API?

'Schuylkill, Pennsylvania'

In [ ]:
# Find the highest trips but lowest ppsqft but hightest growth